#ifndef __VERSION_H_
#define __VERSION_H_ 1

#define BARANIUM_VERSION_YEAR        __YEAR__
#define BARANIUM_VERSION_MONTH       __MONTH__
#define BARANIUM_VERSION_DATE        __DAY__
#define BARANIUM_VERSION_PHASE       "release"

#define VERSION_CREATE(year, month, day) ((year << 16) | (month << 8) | day)

#define VERSION_FIRST VERSION_CREATE(2024, 2, 10)
#define VERSION_FIRST_RELEASE VERSION_CREATE(2025,1,6)
#define VERSION_CURRENT VERSION_CREATE(BARANIUM_VERSION_YEAR, BARANIUM_VERSION_MONTH, BARANIUM_VERSION_DATE)

#endif
